Repository godaddy/asherah, pull requests merged in 2020-06, with the labels that each got.

#225 [Go] Use latest AE in the server and ref-app
  .circleci/config.yml
  samples/go/referenceapp/README.md
  samples/go/referenceapp/go.mod
  samples/go/referenceapp/go.sum
  samples/go/referenceapp/main.go
  server/go/README.md
  server/go/go.mod
  server/go/go.sum
  server/go/pkg/server/options.go
  server/go/pkg/server/server.go
  server/go/pkg/server/server_test.go
Labels: documentation, go

#226 [C#]Add multi-targeting for Logging & AppEncryption
  .circleci/config.yml
  csharp/AppEncryption/AppEncryption.IntegrationTests/AppEncryption.IntegrationTests.csproj
  csharp/AppEncryption/AppEncryption.Tests/AppEncryption.Tests.csproj
  csharp/AppEncryption/AppEncryption/AppEncryption.csproj
  csharp/AppEncryption/Crypto/Crypto.csproj
  csharp/AppEncryption/Directory.Build.props
  csharp/AppEncryption/README.md
  csharp/Logging/Directory.Build.props
  csharp/Logging/Logging.Tests/Logging.Tests.csproj
  csharp/Logging/Logging/Logging.csproj
  csharp/Logging/README.md
  csharp/SecureMemory/SecureMemory.Tests/SecureMemory.Tests.csproj
  samples/csharp/ReferenceApp/ReferenceApp/ReferenceApp.cs
  samples/csharp/ReferenceApp/ReferenceApp/ReferenceApp.csproj
  tests/cross-language/csharp/Cltf.csproj
  tests/cross-language/csharp/scripts/build.sh
  tests/cross-language/scripts/decrypt_all.sh
  tests/cross-language/scripts/encrypt_all.sh
Labels: c#, enhancement

#221 [Java] Use latest AE in the server and ref-app
  docs/Metastore.md
  go/appencryption/README.md
  java/app-encryption/README.md
  samples/java/reference-app/README.md
  samples/java/reference-app/pom.xml
  samples/java/reference-app/src/main/java/com/godaddy/asherah/referenceapp/App.java
  server/go/README.md
  server/java/README.md
  server/java/pom.xml
  server/java/src/main/java/com/godaddy/asherah/grpc/AppEncryptionConfig.java
  server/java/src/main/java/com/godaddy/asherah/grpc/DynamoDbConfig.java
  server/java/src/main/java/com/godaddy/asherah/grpc/ServerApp.java
  server/java/src/test/java/com/godaddy/asherah/grpc/AppEncryptionConfigTest.java
Labels: documentation, java
